name: Bug Report
description: The game crashed or something is not working as expected.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Filling out this information and providing logs will help get the issue resolved faster.
  - type: dropdown
    id: minecraftVersion
    attributes:
      label: Minecraft Version
      description: What version of Minecraft were you running?
      options:
        - 1.19.x
        - 1.18.x
        - 1.17.x
        - 1.16.x
        - Other (specify below)
    validations:
      required: true
  - type: input
    id: modLoaderVersion
    attributes:
      label: Mod Loader Version
      description: What version of Fabric were you using?
    validations:
      required: true
  - type: input
    id: modVersion
    attributes:
      label: Mod Version
      description: What version of the mod were you using?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Be as thorough as possible and provide a step-by-step guide to reproduce the issue.
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: Provide a link to the logs here. You can use a site like pastebin or gist to upload the latest.log content. Make sure they are set to not expire.
  - type: input
    id: otherMods
    attributes:
      label: Do you use any other mods except the required ones?
      description: Test whether the issue happens with all other mods disabled (except the required ones).